[features]
seeds = false
skip-lint = false

[programs.devnet]
donate_protocol = "DonateProtoo11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test --skip-build"
